/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoescolar;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class esqueceusesnha2 extends javax.swing.JFrame {

    /**
     * Creates new form esqueceusesnha2
     */
    public esqueceusesnha2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        profid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        profsenha = new javax.swing.JPasswordField();
        profsenhaok = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        profpalavra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 319));
        getContentPane().setLayout(null);

        profemail.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(profemail);
        profemail.setBounds(150, 100, 200, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Palavra Secreta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 130, 140, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nova senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 130, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Repetir nova senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 170, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usuário ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 120, 20);

        profid.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(profid);
        profid.setBounds(150, 70, 200, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Enviar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 230, 100, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backbutton small3.png"))); // NOI18N
        jLabel5.setText("Voltar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 30, 100, 50);

        profsenha.setBackground(new java.awt.Color(255, 255, 255));
        profsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(profsenha);
        profsenha.setBounds(150, 160, 200, 30);

        profsenhaok.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(profsenhaok);
        profsenhaok.setBounds(150, 190, 200, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Email:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 100, 90, 20);

        profpalavra.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(profpalavra);
        profpalavra.setBounds(150, 130, 200, 30);

        jLabel6.setFont(new java.awt.Font("TlwgMono", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Alterar Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 0, 320, 47);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/colorful_background_7.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -250, 750, 640);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ilive logo small.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 150, 90);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   String id = profid.getText().trim();
        String email = profemail.getText().trim();
        String palavra = profpalavra.getText().trim();
        String senha = profsenha.getText().trim();
        String senha2 = profsenhaok.getText().trim();

        try {
            Connection conn = (Connection) Conexao.obterConexao();
            String checkSql = "SELECT * FROM profcad WHERE ID=? AND email=? AND palavra=?";
            java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql);
            checkStmt.setString(1, id);
            checkStmt.setString(2, email);
            checkStmt.setString(3, palavra);
            ResultSet rs = (ResultSet) checkStmt.executeQuery();

            if (rs.next()) {

                if (senha.equals(senha2)) {

                    String updateSql = "UPDATE profcad SET senha=? WHERE id=?";
                    java.sql.PreparedStatement updateStmt = conn.prepareStatement(updateSql);
                    updateStmt.setString(1, senha);
                    updateStmt.setString(2, id);
                    updateStmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso");
                    dispose();
                } else {

                    JOptionPane.showMessageDialog(null, "As senhas não correspondem. Por favor, digite a mesma senha nos dois campos.");
                }
            } else {

                JOptionPane.showMessageDialog(null, "ID, Palavra Secreta ou Email não encontrado(s). Não foi possível atualizar a senha.");
            }

            Conexao.fecharConexao(conn);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void profsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(esqueceusesnha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(esqueceusesnha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(esqueceusesnha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(esqueceusesnha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new esqueceusesnha2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField profemail;
    private javax.swing.JTextField profid;
    private javax.swing.JTextField profpalavra;
    private javax.swing.JPasswordField profsenha;
    private javax.swing.JPasswordField profsenhaok;
    // End of variables declaration//GEN-END:variables
}
