/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoescolar;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetImpl;
import java.sql.DriverManager;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Gonçalves da Cruz (202412055); Pedro Paulo Lima (324120829); Cayo Marques Macedo (202411215); Maik Douglas de Souza Martins(202410926);  Stella Expedita de Lima(202411513)
 */
public class esqueceusenha extends javax.swing.JFrame {

    /**
     * Creates new form esqueceusenha
     */
    public esqueceusenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        estusenha = new javax.swing.JPasswordField();
        estusenhaok = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        estuemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        estupalavra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 319));
        setPreferredSize(new java.awt.Dimension(506, 293));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nova senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 163, 100, 17);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Repetir nova senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 197, 170, 17);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 55, 60, 17);

        estura.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estura);
        estura.setBounds(180, 50, 200, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Enviar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 230, 100, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backbutton small3.png"))); // NOI18N
        jLabel5.setText("Voltar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 0, 100, 50);

        estusenha.setBackground(new java.awt.Color(255, 255, 255));
        estusenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estusenhaActionPerformed(evt);
            }
        });
        getContentPane().add(estusenha);
        estusenha.setBounds(180, 155, 200, 30);

        estusenhaok.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estusenhaok);
        estusenhaok.setBounds(180, 190, 200, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Email:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(130, 92, 70, 17);

        estuemail.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estuemail);
        estuemail.setBounds(180, 85, 200, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Palavra Secreta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 127, 140, 17);

        estupalavra.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estupalavra);
        estupalavra.setBounds(180, 120, 200, 30);

        jLabel6.setFont(new java.awt.Font("TlwgMono", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Alterar Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 0, 300, 45);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/colorful_background_7.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -250, 750, 640);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ilive logo small.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 150, 90);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String id = estura.getText().trim();
       String email = estuemail.getText().trim();
       String palavra = estupalavra.getText().trim();
String senha = estusenha.getText().trim();
String senha2 = estusenhaok.getText().trim();

try {
    Connection conn = (Connection) projetoescolar.Conexao.obterConexao();
    String checkSql = "SELECT * FROM estucad WHERE ID=? AND email=? AND palavra=?";
           java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql);
    checkStmt.setString(1, id);
    checkStmt.setString(2, email);
    checkStmt.setString(3, palavra);
    ResultSetImpl rs = (ResultSetImpl) checkStmt.executeQuery();

    if (rs.next()) {
 
        if (senha.equals(senha2)) {
            
            String updateSql = "UPDATE estucad SET senha=? WHERE id=?";
            java.sql.PreparedStatement updateStmt = conn.prepareStatement(updateSql);
            updateStmt.setString(1, senha);
            updateStmt.setString(2, id);
            updateStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso");
            dispose();
        } else {
            
            JOptionPane.showMessageDialog(null, "As senhas não correspondem. Por favor, digite a mesma senha nos dois campos.");
        }
    } else {
        
        JOptionPane.showMessageDialog(null, "RA, Palavra Secreta ou Email não encontrado(s). Não foi possível atualizar a senha.");
    }

    projetoescolar.Conexao.fecharConexao(conn);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);


  
  
}

        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void estusenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estusenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estusenhaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(esqueceusenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(esqueceusenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(esqueceusenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(esqueceusenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new esqueceusenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estuemail;
    private javax.swing.JTextField estupalavra;
    private javax.swing.JTextField estura;
    private javax.swing.JPasswordField estusenha;
    private javax.swing.JPasswordField estusenhaok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
