/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoescolar;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class extensaoestu extends javax.swing.JFrame {

    /**
     * Creates new form extensaoestu
     */
    public extensaoestu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        dispreg = new javax.swing.JTextField();
        displist = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 345));
        getContentPane().setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Extensão:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(41, 68, 90, 22);

        dispreg.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dispreg);
        dispreg.setBounds(41, 136, 317, 22);

        displist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco De Dados", "Mat. Basica", "Fotografia" }));
        displist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displistActionPerformed(evt);
            }
        });
        getContentPane().add(displist);
        displist.setBounds(41, 102, 317, 22);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Registrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(238, 170, 120, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backbutton small3.png"))); // NOI18N
        jLabel1.setText("Voltar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 6, 100, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/colorful_background_7.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-4910, -2690, 5334, 3000);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       menuestu obj = new menuestu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void displistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displistActionPerformed
      String disciplinaSelecionada = displist.getSelectedItem().toString();
        dispreg.setText(disciplinaSelecionada);
    }//GEN-LAST:event_displistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String raAluno = SessaoAluno.getInstancia().getRaAluno();


String disciplinaSelecionada = (String) dispreg.getText();

Connection conn = null;
PreparedStatement stmt = null;
ResultSetImpl rs = null;

try {
    conn = (Connection) Conexao.obterConexao();

    
    String verificarExistenciaSql = "SELECT COUNT(*) FROM extensao WHERE id = ?";
    stmt = (PreparedStatement) conn.prepareStatement(verificarExistenciaSql);
    stmt.setString(1, raAluno);
    rs = (ResultSetImpl) stmt.executeQuery();

    rs.next();
    int rowCount = rs.getInt(1);

    if (rowCount > 0) {
        JOptionPane.showMessageDialog(this, "Extensão já registrada para este aluno.");
        return;
    }

    String consultaNomeAlunoSql = "SELECT nome FROM estucad WHERE id = ?";
    stmt = (PreparedStatement) conn.prepareStatement(consultaNomeAlunoSql);
    stmt.setString(1, raAluno); // Filtra pelo RA do aluno
    rs = (ResultSetImpl) stmt.executeQuery();

    String nomeAluno = null;

    if (rs.next()) {
        nomeAluno = rs.getString("nome");
    } else {
        JOptionPane.showMessageDialog(this, "Nome do aluno não encontrado para o RA informado.");
        return;
    }

    
    String inserirExtensaoSql = "INSERT INTO extensao (nome, id, extensao) VALUES (?, ?, ?)";
    stmt = (PreparedStatement) conn.prepareStatement(inserirExtensaoSql);
    stmt.setString(1, nomeAluno); 
    stmt.setString(2, raAluno); 
    stmt.setString(3, disciplinaSelecionada); 

    int linhasAfetadas = stmt.executeUpdate();

    if (linhasAfetadas > 0) {
        JOptionPane.showMessageDialog(this, "Registro concluído.");
    } else {
        JOptionPane.showMessageDialog(this, "Falha ao registrar.");
    }

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erro ao registrar: " + e.getMessage());
} finally {
    try {
        if (rs != null) rs.close();
        if (stmt != null) stmt.close();
        if (conn != null) conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(extensaoestu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(extensaoestu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(extensaoestu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(extensaoestu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new extensaoestu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> displist;
    private javax.swing.JTextField dispreg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
