/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoescolar;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSetImpl;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Arrays;

/**
 *
 * @author Lucas
 */
public class primeiroacesso extends javax.swing.JFrame {

    /**
     * Creates new form palavrasecreta
     */
    public primeiroacesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        estura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estuemail = new javax.swing.JTextField();
        estusenha = new javax.swing.JPasswordField();
        estusenhaok = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        estusenha1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 379));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RA:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 27, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Enviar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 300, 90, 30);

        estura.setBackground(new java.awt.Color(255, 255, 255));
        estura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esturaActionPerformed(evt);
            }
        });
        getContentPane().add(estura);
        estura.setBounds(170, 102, 410, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Repetir nova senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 159, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nova senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 98, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 46, 30);

        estuemail.setBackground(new java.awt.Color(255, 255, 255));
        estuemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estuemailActionPerformed(evt);
            }
        });
        getContentPane().add(estuemail);
        estuemail.setBounds(170, 140, 410, 30);

        estusenha.setBackground(new java.awt.Color(255, 255, 255));
        estusenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estusenhaActionPerformed(evt);
            }
        });
        getContentPane().add(estusenha);
        estusenha.setBounds(170, 220, 410, 30);

        estusenhaok.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estusenhaok);
        estusenhaok.setBounds(170, 260, 410, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backbutton small3.png"))); // NOI18N
        jLabel6.setText("Voltar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 20, 100, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Senha cadastrada:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 180, 147, 30);

        estusenha1.setBackground(new java.awt.Color(255, 255, 255));
        estusenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estusenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(estusenha1);
        estusenha1.setBounds(170, 180, 410, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ilive logo small.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 150, 90);

        jLabel5.setFont(new java.awt.Font("TlwgMono", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Primeiro Acesso");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 10, 340, 45);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/colorful_background_7.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-1220, -260, 1900, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void esturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esturaActionPerformed
      
        
    }//GEN-LAST:event_esturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String id = estura.getText().trim();
String email = estuemail.getText().trim();
String senhaAtual = estusenha1.getText().trim();
String novaSenha = estusenha.getText().trim();
String novaSenhaRepetir = estusenhaok.getText().trim();

try {
    Connection conn = (Connection) projetoescolar.Conexao.obterConexao();
    String checkSql = "SELECT senha FROM estucad WHERE ID=? AND email=?";
    java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql);
    checkStmt.setString(1, id);
    checkStmt.setString(2, email);
    ResultSet rs = checkStmt.executeQuery();

    if (rs.next()) {
        // Verifica se a senha atual fornecida pelo usuário corresponde à senha armazenada no banco de dados
        String senhaCadastrada = rs.getString("senha");
        if (senhaAtual.equals(senhaCadastrada)) {
            // Se a senha atual corresponde, verifica se a nova senha e a confirmação coincidem
            if (novaSenha.equals(novaSenhaRepetir)) {
                // Atualiza a senha no banco de dados
                String updateSql = "UPDATE estucad SET senha=? WHERE ID=?";
                java.sql.PreparedStatement updateStmt = conn.prepareStatement(updateSql);
                updateStmt.setString(1, novaSenha);
                updateStmt.setString(2, id);
                updateStmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Primeiro Acesso Concedido");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "As novas senhas não correspondem. Por favor, digite a mesma senha nos dois campos.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha atual incorreta.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "RA ou Email não encontrado(s). Não foi possível realizar o primeiro acesso.");
    }

    projetoescolar.Conexao.fecharConexao(conn);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro ao acessar o banco de dados: " + e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void estuemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estuemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estuemailActionPerformed

    private void estusenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estusenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estusenhaActionPerformed

    private void estusenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estusenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estusenha1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primeiroacesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primeiroacesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primeiroacesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primeiroacesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primeiroacesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estuemail;
    private javax.swing.JTextField estura;
    private javax.swing.JPasswordField estusenha;
    private javax.swing.JPasswordField estusenha1;
    private javax.swing.JPasswordField estusenhaok;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
